import json
import re
from langchain_core.tools import tool
from app.detectors import (
    phishing_detector,
    url_analyzer,
    prompt_injection_detector,
    anomaly_detector,
    ai_content_detector,
)


@tool
def analyze_phishing_text(text: str) -> str:
    """Analyze an email or message for phishing language, urgency manipulation, financial scams, and social engineering patterns."""
    features = phishing_detector.extract_phishing_features(text)
    risk_score, feature_weights = phishing_detector.compute_phishing_risk(features)
    signals = phishing_detector.get_phishing_signals(features)
    highlights = phishing_detector.get_phishing_highlights(text)
    return json.dumps({
        "risk_score": round(risk_score, 1),
        "signals": signals,
        "feature_weights": feature_weights,
        "highlighted_segments": highlights,
        "threat_type": "Phishing Email / Message"
    })


@tool
def extract_urls_from_text(text: str) -> str:
    """Extract all URLs found inside a block of text. Call this on email content before analyzing individual URLs."""
    urls = re.findall(r'https?://[^\s<>"\']+|www\.[^\s<>"\']+', text)
    return json.dumps({"urls": urls[:5], "count": len(urls)})


@tool
def analyze_url(url: str) -> str:
    """Analyze a single URL for malicious indicators: suspicious TLD, IP domain, phishing keywords, excessive subdomains, redirect chains."""
    features = url_analyzer.extract_url_features(url.strip())
    risk_score, feature_weights, signals = url_analyzer.compute_url_risk_score(features)
    highlights = url_analyzer.get_url_highlights(url, features)
    return json.dumps({
        "url": url,
        "risk_score": round(risk_score, 1),
        "signals": signals,
        "feature_weights": feature_weights,
        "highlighted_segments": highlights,
        "threat_type": "Malicious URL"
    })


@tool
def detect_prompt_injection(text: str) -> str:
    """Detect if a text input attempts to inject malicious instructions into an AI system — instruction overrides, jailbreaks, role-switching, delimiter injection."""
    result = prompt_injection_detector.detect_prompt_injection(text)
    return json.dumps({
        "risk_score": result["risk_score"],
        "signals": result["signals"],
        "feature_weights": result["matched_patterns"],
        "highlighted_segments": result["highlighted_segments"],
        "threat_type": "Prompt Injection Attack"
    })


@tool
def detect_anomalous_login(log_json: str) -> str:
    """Analyze a JSON array of login events to detect brute force, impossible travel, off-hours access, and rapid session chaining. Input must be a JSON string."""
    result = anomaly_detector.detect(log_json)
    return json.dumps(result)


@tool
async def detect_ai_generated_content(text: str) -> str:
    """Detect if text was generated by an AI system and used for deceptive purposes — checks sentence uniformity, lexical diversity, repetition patterns, and uses an LLM judge."""
    result = await ai_content_detector.detect(text)
    return json.dumps(result)


ALL_TOOLS = [
    analyze_phishing_text,
    extract_urls_from_text,
    analyze_url,
    detect_prompt_injection,
    detect_anomalous_login,
    detect_ai_generated_content,
]
